
services:
    mongo:
        image: mongo
        container_name: mongodb
        ports:
        - 27017:27017
        volumes:
        - mongo:/data
        environment:
            - MONGO_INITDB_ROOT_USERNAME=Rafael
            - MONGO_INITDB_ROOT_PASSWORD=ads2023
    mongo-express:
        image: mongo-express
        container_name: mongo_express
        ports:
          - "8081:8081"
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
            - ME_CONFIG_MONGODB_ADMINUSERNAME=Rafael
            - ME_CONFIG_MONGODB_ADMINPASSWORD=ads2023
            - ME_CONFIG_BASICAUTH_USERNAME=Rafael
            - ME_CONFIG_BASICAUTH_PASSWORD=ads2023
volumes:
 mongo: {}
        